config/routes.rb
Rails.application.routes.draw do
  get '/redirect', to: 'example#redirect', as: 'redirect'
  get '/callback', to: 'example#callback', as: 'callback'
  get '/calendars', to: 'example#calendars', as: 'calendars'
  get '/events/:calendar_id', to: 'example#events', as: 'events', calendar_id: /[^\/]+/
  post '/events/:calendar_id', to: 'example#new_event', as: 'new_event', calendar_id: /[^\/]+/
  root "example#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/example_controller.rb
class ExampleController < ApplicationController
    def redirect
      client = Signet::OAuth2::Client.new(client_options)
  
      redirect_to client.authorization_uri.to_s ,allow_other_host: true
    end


    def callback
        client = Signet::OAuth2::Client.new(client_options)
        client.code = params[:code]
    
        response = client.fetch_access_token!
    
        session[:authorization] = response
    
        redirect_to calendars_url
    end

    def calendars
        client = Signet::OAuth2::Client.new(client_options)
        client.update!(session[:authorization])
    
        service = Google::Apis::CalendarV3::CalendarService.new
        service.authorization = client
    
        @calendar_list = service.list_calendar_lists

       rescue Google::Apis::AuthorizationError
        response = client.refresh!
    
        session[:authorization] = session[:authorization].merge(response)
    
        retry
      end

      def events
        client = Signet::OAuth2::Client.new(client_options)
        client.update!(session[:authorization])
    
        service = Google::Apis::CalendarV3::CalendarService.new
        service.authorization = client
    
        @event_list = service.list_events(params[:calendar_id])
      end

      def new_event
        client = Signet::OAuth2::Client.new(client_options)
        client.update!(session[:authorization])
    
        service = Google::Apis::CalendarV3::CalendarService.new
        service.authorization = client
    
        today = Date.today
        
     
          event = Google::Apis::CalendarV3::Event.new(
            start: Google::Apis::CalendarV3::EventDateTime.new(date: params[:startdate]),
            end: Google::Apis::CalendarV3::EventDateTime.new(date: params[:enddate]),
            summary: params[:summary]
          )
    
        service.insert_event(params[:calendar_id], event)
    
        redirect_to events_url(calendar_id: params[:calendar_id])
      end
  
    private
    
    def client_options
      {
        client_id: Rails.application.secrets.google_client_id,
        client_secret: Rails.application.secrets.google_client_secret,
        authorization_uri: 'https://accounts.google.com/o/oauth2/auth',
        token_credential_uri: 'https://accounts.google.com/o/oauth2/token',
        scope: Google::Apis::CalendarV3::AUTH_CALENDAR,
        redirect_uri: callback_url
      }
    end
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/example_helper.rb
module ExampleHelper
end

app/views/example/add_event.html.erb
<%= form_with url: "/events/:calendar_id" , method: :post do |form| %>
 <%= form.text_field :summary %>
 <%= form.submit “Create” %>
<% end %>

app/views/example/calendars.html.erb
<ul>
  <% @calendar_list.items.each do |calendar| %>

    <li><%= link_to calendar.summary, events_path(calendar.id) %> (<%= calendar.id %>)</li>
  <% end %>
</ul>

app/views/example/events.html.erb
<ul>
  <% @event_list.items.each do |event| %>
    <li><%= event.summary %> </li>
  <% end %>
</ul>



<%= form_with url: new_event_url do |form| %>
 <%= form.text_field :summary %>
 <%= form.date_field :startdate %>
 <%= form.date_field :enddate%>

 <%= form.submit  %>
<% end %>

app/views/example/index.html.erb
<p>Dummy App</p>


<%= link_to "Login with google", redirect_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GoogleCalenderIntegration</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>